{{/* ConfigMap for Coordinator application config */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agora.fullname" . }}-config
  labels:
    {{- include "agora.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
data:
  AGORA_WORKSPACE_BACKEND: {{ .Values.workspace.storage.backend | quote }}
  {{- if .Values.workspace.storage.backend | eq "s3" }}
  AGORA_S3_BUCKET: {{ .Values.workspace.s3.bucket | quote }}
  AGORA_S3_ENDPOINT: {{ .Values.workspace.s3.endpoint | quote }}
  {{- end }}
