{{/* Secret for embedded Postgres password */}}
{{- if and .Values.database.embedded.enabled (not .Values.database.externalUrl) }}
{{- if .Values.database.embedded.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agora.fullname" . }}-db
  labels:
    {{- include "agora.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
data:
  password: {{ .Values.database.embedded.password | b64enc | quote }}
{{- end }}
{{- end }}
