#!/usr/bin/env bash
# Agora — One-line installer
# Usage: curl -fsSL https://raw.githubusercontent.com/yzy806806/agora/main/install.sh | bash
#         curl -fsSL ... | bash -s -- --matrix    # with Matrix support
set -euo pipefail

# ── Colors ──────────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
  GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'
  CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
else
  GREEN=''; YELLOW=''; RED=''; CYAN=''; BOLD=''; NC=''
fi
info()  { printf "${GREEN}✓${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}⚠${NC} %s\n" "$*" >&2; }
err()   { printf "${RED}✗${NC} %s\n" "$*" >&2; }
step()  { printf "${CYAN}▶${NC} ${BOLD}%s${NC}\n" "$*"; }

# ── Config ──────────────────────────────────────────────────────────────────
AGORA_HOME="${HOME}/.agora"
AGORA_VENV="${AGORA_HOME}/venv"
AGORA_BIN_DIR="${HOME}/.local/bin"
AGORA_REPO="https://github.com/yzy806806/agora"
INSTALL_MATRIX=false

# Parse args
for arg in "$@"; do
  case "$arg" in
    --matrix) INSTALL_MATRIX=true ;;
    --help|-h)
      echo "Usage: curl -fsSL .../install.sh | bash -s -- [--matrix]"
      exit 0 ;;
  esac
done

# ── Preflight ───────────────────────────────────────────────────────────────
step "Checking system dependencies..."

# Python 3.11+
PYTHON=""
for cmd in python3.12 python3.11 python3; do
  if command -v "$cmd" &>/dev/null; then
    ver="$("$cmd" -c 'import sys;print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null || echo 0)"
    major="${ver%%.*}"; minor="${ver#*.}"
    if [[ "$major" -eq 3 && "$minor" -ge 11 ]]; then
      PYTHON="$cmd"; break
    fi
  fi
done
if [[ -z "$PYTHON" ]]; then
  err "Python 3.11+ required. Found: $(python3 --version 2>&1 || echo 'none')"
  err "Install Python 3.11+ and retry."
  exit 1
fi
info "Python: $("$PYTHON" --version 2>&1)"

# ── Install uv (if missing) ────────────────────────────────────────────────
if ! command -v uv &>/dev/null; then
  step "Installing uv (fast Python package manager)..."
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.cargo/bin:${HOME}/.local/bin:${PATH}"
  if ! command -v uv &>/dev/null; then
    err "Failed to install uv. Please install manually: https://docs.astral.sh/uv/"
    exit 1
  fi
  info "uv installed: $(uv --version)"
else
  info "uv already installed: $(uv --version)"
fi

# ── Create directories ─────────────────────────────────────────────────────
step "Creating Agora directory structure..."
mkdir -p "${AGORA_HOME}/data" "${AGORA_HOME}/agents" "${AGORA_BIN_DIR}"
info "Home: ${AGORA_HOME}"

# ── Clone or update repo ───────────────────────────────────────────────────
AGORA_SRC="${AGORA_HOME}/src"
if [[ -d "${AGORA_SRC}/.git" ]]; then
  step "Updating existing Agora source..."
  git -C "${AGORA_SRC}" pull --ff-only || warn "Git pull failed, using existing source"
else
  step "Cloning Agora repository..."
  git clone --depth 1 "${AGORA_REPO}.git" "${AGORA_SRC}"
fi
info "Source: ${AGORA_SRC}"

# ── Create venv & install ──────────────────────────────────────────────────
step "Creating virtual environment..."
uv venv "${AGORA_VENV}" --python "${PYTHON}"
info "Venv: ${AGORA_VENV}"

EXTRA=""
if [[ "$INSTALL_MATRIX" == true ]]; then
  step "Installing with Matrix support (matrix-nio)..."
  EXTRA="--extra matrix"
else
  step "Installing Agora + dependencies..."
fi

# shellcheck disable=SC2086
uv pip install --python "${AGORA_VENV}/bin/python" ${EXTRA} -e "${AGORA_SRC}"
info "Dependencies installed"

# ── Generate default config ────────────────────────────────────────────────
CONFIG_FILE="${AGORA_HOME}/config.yaml"
if [[ ! -f "${CONFIG_FILE}" ]]; then
  step "Generating default config..."
  cat > "${CONFIG_FILE}" << 'YAML'
# Agora Coordinator configuration
# Priority: CLI args > env vars (AGORA_*) > this file > defaults

host: "0.0.0.0"
port: 8765
debug: false

db_path: "~/.agora/data/agora.db"
database:
  backend: "sqlite"
  db_path: "~/.agora/data/agora.db"

log_level: "INFO"
cors_origins: ["*"]

auth_mode: "none"
require_approval: false

default_rounds: 3
heartbeat_interval_seconds: 30
heartbeat_timeout_seconds: 120
YAML
  info "Config: ${CONFIG_FILE}"
else
  info "Config exists, keeping: ${CONFIG_FILE}"
fi

# ── Register `agora` command to PATH ───────────────────────────────────────
step "Registering 'agora' command..."
WRAPPER="${AGORA_BIN_DIR}/agora"
cat > "${WRAPPER}" << EOF
#!/usr/bin/env bash
# Auto-generated by Agora installer
exec "${AGORA_VENV}/bin/python" -m agora.coordinator.cli "\$@"
EOF
chmod +x "${WRAPPER}"

# Ensure ~/.local/bin is in PATH
if [[ ":${PATH}:" != *":${AGORA_BIN_DIR}:"* ]]; then
  warn "${AGORA_BIN_DIR} is not in your PATH."
  SHELL_NAME="$(basename "${SHELL:-/bin/bash}")"
  case "$SHELL_NAME" in
    zsh) RC_FILE="${HOME}/.zshrc" ;;
    *)   RC_FILE="${HOME}/.bashrc" ;;
  esac
  echo 'export PATH="${HOME}/.local/bin:${PATH}"' >> "${RC_FILE}"
  info "Added ~/.local/bin to PATH in ${RC_FILE}"
  warn "Run: source ${RC_FILE}  (or restart your shell)"
fi
info "Command: ${WRAPPER}"

# ── Done ────────────────────────────────────────────────────────────────────
echo ""
printf "${GREEN}${BOLD}✓ Agora installed successfully!${NC}\n"
echo ""
echo "  Quick start:"
echo "    agora init      # Interactive setup wizard"
echo "    agora serve     # Start the coordinator server"
echo "    agora agent add --name my-agent  # Register an agent"
echo "    agora version   # Check installation"
echo ""
if [[ "$INSTALL_MATRIX" == true ]]; then
  echo "  Matrix support installed. Configure with:"
  echo "    agora init --enable-matrix"
  echo ""
fi
echo "  Dashboard: http://localhost:8765/dashboard"
echo "  MCP endpoint: http://localhost:8765/mcp"
echo ""
