"""Agora CLI — command-line interface for the Agora platform.

Subcommands:
    agora init              Interactive setup wizard → ~/.agora/config.yaml
    agora serve             Start the coordinator server (uvicorn)
    agora agent add         Register a new agent (generates Hermes profile config)
    agora agent list        List registered agents
    agora version           Show version info
    agora daemon            Run the bootstrap daemon
    agora migrate           Migrate SQLite → Postgres

Config priority: CLI args > env vars (AGORA_*) > ~/.agora/config.yaml > defaults
"""
from __future__ import annotations

import argparse
import json
import os
import secrets
import sys
from pathlib import Path
from typing import Any

# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------

AGORA_HOME = Path.home() / ".agora"
AGORA_CONFIG = AGORA_HOME / "config.yaml"
AGORA_AGENTS_DIR = AGORA_HOME / "agents"

# ANSI colors (auto-disabled when not a TTY)
_USE_COLOR = sys.stdout.isatty()


def _c(code: str, text: str) -> str:
    if not _USE_COLOR:
        return text
    return f"\033[{code}m{text}\033[0m"

GREEN = lambda t: _c("32", t)   # noqa: E731
RED   = lambda t: _c("31", t)   # noqa: E731
CYAN  = lambda t: _c("36", t)   # noqa: E731
YELLOW = lambda t: _c("33", t)  # noqa: E731
BOLD  = lambda t: _c("1", t)   # noqa: E731


def _info(msg: str) -> None:
    print(f"{GREEN('✓')} {msg}")


def _warn(msg: str) -> None:
    print(f"{YELLOW('⚠')} {msg}")


def _err(msg: str) -> None:
    print(f"{RED('✗')} {msg}", file=sys.stderr)


def _prompt(question: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        val = input(f"{CYAN('?')} {question}{suffix}: ").strip()
    except (EOFError, KeyboardInterrupt):
        val = ""
    return val or default


def _prompt_bool(question: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    val = _prompt(question, d)
    return val.lower() in ("y", "yes", "true", "1")


def _ensure_dirs() -> None:
    AGORA_HOME.mkdir(parents=True, exist_ok=True)
    AGORA_AGENTS_DIR.mkdir(parents=True, exist_ok=True)
    (AGORA_HOME / "data").mkdir(parents=True, exist_ok=True)


# ----------------------------------------------------------------------------
# Config generation
# ----------------------------------------------------------------------------

_DEFAULT_CONFIG = """\
# Agora Coordinator configuration
# Priority: CLI args > env vars (AGORA_*) > this file > defaults
# Generated by `agora init`

# Service
host: "{host}"
port: {port}
debug: false

# Database
db_path: "~/.agora/data/agora.db"
database:
  backend: "sqlite"
  db_path: "~/.agora/data/agora.db"

# Logging
log_level: "INFO"

# CORS
cors_origins:
  - "*"

# Auth (none | token | rbac)
auth_mode: "{auth_mode}"
require_approval: {require_approval}

# Discussion defaults
default_rounds: 3
default_voting_method: "simple_majority"

# Heartbeat
heartbeat_interval_seconds: 30
heartbeat_timeout_seconds: 120
"""


def _generate_config(
    host: str,
    port: int,
    auth_mode: str,
    require_approval: bool,
) -> str:
    return _DEFAULT_CONFIG.format(
        host=host,
        port=port,
        auth_mode=auth_mode,
        require_approval=str(require_approval).lower(),
    )


# ----------------------------------------------------------------------------
# Subcommands
# ----------------------------------------------------------------------------

def _cmd_init(args: argparse.Namespace) -> None:
    """Interactive setup wizard → ~/.agora/config.yaml."""
    print(f"\n{BOLD('Agora Init — Interactive Setup')}\n")
    _ensure_dirs()

    host = _prompt("Bind host", "0.0.0.0")
    port = int(_prompt("Bind port", "8765"))

    print(f"\n  {YELLOW('Auth modes:')}")
    print(f"    none  — no auth (dev only)")
    print(f"    token — Bearer token required")
    print(f"    rbac  — full RBAC with roles")
    auth_mode = _prompt("Auth mode", "none")

    require_approval = _prompt_bool("Require agent approval?", default=True)

    # Matrix (optional)
    enable_matrix = getattr(args, "enable_matrix", False)
    if not enable_matrix:
        enable_matrix = _prompt_bool("Enable Matrix wakeup? (advanced)", default=False)

    config_text = _generate_config(host, port, auth_mode, require_approval)

    if enable_matrix:
        print(f"\n  {CYAN('Matrix wakeup configuration:')}")
        mx_homeserver = _prompt("Matrix homeserver URL", "http://localhost:8008")
        mx_token = _prompt("Matrix access token", "")
        mx_room = _prompt("Matrix wakeup room ID", "")
        config_text += f"""
# Matrix wakeup
matrix_homeserver_url: "{mx_homeserver}"
matrix_access_token: "{mx_token}"
matrix_wakeup_room_id: "{mx_room}"
"""

    config_path = AGORA_CONFIG
    if config_path.exists() and not _prompt_bool("Config exists. Overwrite?", default=False):
        _warn("Keeping existing config.")
    else:
        config_path.write_text(config_text, encoding="utf-8")
        _info(f"Config written to {config_path}")

    _info(f"Agora home: {AGORA_HOME}")
    print(f"\n{GREEN('Done!')} Run {BOLD('agora serve')} to start.\n")


def _cmd_serve(args: argparse.Namespace) -> None:
    """Start the Agora coordinator server via uvicorn."""
    import uvicorn
    from agora.coordinator.config import settings

    host = args.host or settings.host
    port = args.port or settings.port
    reload = args.reload or settings.debug

    print(f"{BOLD('Starting Agora Coordinator')}")
    print(f"  Host: {host}")
    print(f"  Port: {port}")
    print(f"  Reload: {reload}")
    print(f"  Config: {AGORA_CONFIG}\n")

    uvicorn.run(
        "agora.coordinator.main:app",
        host=host,
        port=port,
        reload=reload,
        log_level=settings.log_level.lower(),
    )


def _cmd_version(args: argparse.Namespace) -> None:
    """Display version information."""
    from agora import __version__
    import platform
    import sys as _sys

    print(f"{BOLD('agora')} {__version__}")
    print(f"  Python: {_sys.version.split()[0]} ({platform.machine()})")
    print(f"  Platform: {platform.system()} {platform.release()}")
    print(f"  Config: {AGORA_CONFIG}")

    # Show install location
    try:
        import agora as _agora
        print(f"  Location: {Path(_agora.__file__).parent}")
    except Exception:
        pass

    # Check if server is reachable
    try:
        import httpx
        from agora.coordinator.config import settings
        # Use 127.0.0.1 since 0.0.0.0 is a bind address, not connectable
        check_host = "127.0.0.1" if settings.host in ("0.0.0.0", "::", "") else settings.host
        url = f"http://{check_host}:{settings.port}/api/v1/health"
        r = httpx.get(url, timeout=2.0)
        if r.status_code == 200:
            data = r.json()
            print(f"  Server: {GREEN('running')} (v{data.get('version', '?')})")
        else:
            print(f"  Server: {YELLOW('unreachable')} (HTTP {r.status_code})")
    except Exception:
        print(f"  Server: {YELLOW('not running')}")


def _cmd_agent_add(args: argparse.Namespace) -> None:
    """Register a new agent — generates Hermes profile config."""
    _ensure_dirs()

    name = args.name
    role = args.role

    # Generate a token
    token = secrets.token_urlsafe(32)

    # Determine coordinator URL
    host = args.host or "localhost"
    port = args.port or 8765
    base_url = f"http://{host}:{port}"

    # Agent record
    agent_record = {
        "name": name,
        "role": role,
        "token": token,
        "coordinator_url": base_url,
        "mcp_url": f"{base_url}/mcp",
    }

    # Save agent record
    agent_file = AGORA_AGENTS_DIR / f"{name}.json"
    agent_file.write_text(
        json.dumps(agent_record, indent=2) + "\n",
        encoding="utf-8",
    )

    # Generate Hermes profile config snippet
    hermes_config = f"""# Hermes profile config for agent: {name}
# Add this to ~/.hermes/config.yaml under mcp_servers:
#
# mcp_servers:
#   agora:
#     url: "{base_url}/mcp"
#     headers:
#       Authorization: "Bearer {token}"
#     timeout: 300

# Or save as a standalone profile:
#   mkdir -p ~/.hermes/profiles/{name}
#   cp this file to ~/.hermes/profiles/{name}/config.yaml

mcp_servers:
  agora:
    url: "{base_url}/mcp"
    headers:
      Authorization: "Bearer {token}"
    timeout: 300
"""

    hermes_file = AGORA_AGENTS_DIR / f"{name}-hermes.yaml"
    hermes_file.write_text(hermes_config, encoding="utf-8")

    _info(f"Agent '{name}' registered (role: {role})")
    print(f"  Token: {token[:16]}...{token[-8:]}")
    print(f"  Agent record: {agent_file}")
    print(f"  Hermes config: {hermes_file}")
    print(f"  MCP URL: {base_url}/mcp")
    print()
    print(f"{CYAN('Next steps:')}")
    print(f"  1. Start the server:  agora serve")
    print(f"  2. Configure Hermes:  cp {hermes_file} ~/.hermes/config.yaml")
    print(f"  3. Agent connects via MCP and auto-registers\n")


def _cmd_agent_list(args: argparse.Namespace) -> None:
    """List registered agents."""
    if not AGORA_AGENTS_DIR.exists():
        _warn("No agents directory found. Run 'agora agent add' first.")
        return

    agents = sorted(AGORA_AGENTS_DIR.glob("*.json"))
    if not agents:
        _warn("No agents registered.")
        return

    print(f"\n{BOLD('Registered Agents')}")
    print(f"{'─' * 60}")
    print(f"{'Name':<20} {'Role':<12} {'Token (truncated)':<28}")
    print(f"{'─' * 60}")

    for f in agents:
        try:
            data = json.loads(f.read_text(encoding="utf-8"))
            name = data.get("name", f.stem)
            role = data.get("role", "?")
            token = data.get("token", "")
            tok_display = f"{token[:12]}...{token[-6:]}" if len(token) > 20 else token
            print(f"{name:<20} {role:<12} {tok_display:<28}")
        except (json.JSONDecodeError, KeyError):
            _warn(f"  Skipping malformed: {f.name}")

    print(f"{'─' * 60}")
    print(f"Total: {len(agents)} agent(s)\n")


def _cmd_daemon(args: argparse.Namespace) -> None:
    """Run the bootstrap daemon."""
    import asyncio
    from agora.coordinator.config import settings
    from agora.coordinator.bootstrap.daemon import run_daemon

    db_path = settings.get_db_path()
    coordinator_url = f"http://{settings.host}:{settings.port}"

    asyncio.run(run_daemon(
        db_path=db_path,
        coordinator_url=coordinator_url,
        interval_minutes=args.interval,
        dry_run=args.dry_run,
        once=args.once,
    ))


# ----------------------------------------------------------------------------
# Parser
# ----------------------------------------------------------------------------

def build_parser() -> argparse.ArgumentParser:
    """Build the argument parser for the agora CLI."""
    from agora import __version__

    parser = argparse.ArgumentParser(
        prog="agora",
        description="Agora — Multi-Agent Deliberation Platform",
    )
    parser.add_argument(
        "--version", action="version",
        version=f"agora {__version__}",
    )

    sub = parser.add_subparsers(dest="command")

    # init
    sp_init = sub.add_parser("init", help="Interactive setup wizard")
    sp_init.add_argument("--enable-matrix", action="store_true",
                         help="Enable Matrix wakeup configuration")
    sp_init.set_defaults(func=_cmd_init)

    # serve
    sp_serve = sub.add_parser("serve", help="Start the coordinator server")
    sp_serve.add_argument("--host", default=None, help="Bind host")
    sp_serve.add_argument("--port", type=int, default=None, help="Bind port")
    sp_serve.add_argument("--reload", action="store_true",
                          help="Enable auto-reload (dev mode)")
    sp_serve.set_defaults(func=_cmd_serve)

    # version
    sp_version = sub.add_parser("version", help="Show version info")
    sp_version.set_defaults(func=_cmd_version)

    # agent
    sp_agent = sub.add_parser("agent", help="Agent management")
    sp_agent_sub = sp_agent.add_subparsers(dest="agent_command")

    # agent add
    sp_add = sp_agent_sub.add_parser("add", help="Register a new agent")
    sp_add.add_argument("--name", required=True, help="Agent name")
    sp_add.add_argument("--role", choices=["moderator", "worker"],
                        default="worker", help="Agent role (default: worker)")
    sp_add.add_argument("--host", default=None,
                        help="Coordinator host (default: localhost)")
    sp_add.add_argument("--port", type=int, default=None,
                        help="Coordinator port (default: 8765)")
    sp_add.set_defaults(func=_cmd_agent_add)

    # agent list
    sp_list = sp_agent_sub.add_parser("list", help="List registered agents")
    sp_list.set_defaults(func=_cmd_agent_list)

    # daemon
    sp_daemon = sub.add_parser("daemon", help="Run the bootstrap daemon")
    sp_daemon.add_argument("--interval", type=int, default=30,
                           help="Check interval in minutes (default: 30)")
    sp_daemon.add_argument("--dry-run", action="store_true",
                           help="Only detect work, don't execute")
    sp_daemon.add_argument("--once", action="store_true",
                           help="Run once and exit (no loop)")
    sp_daemon.set_defaults(func=_cmd_daemon)

    # migrate
    from agora.cli_migrate import add_migrate_parser
    add_migrate_parser(sub)

    return parser


def main() -> None:
    """CLI entry point."""
    parser = build_parser()
    args = parser.parse_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    # `agora agent` without subcommand
    if args.command == "agent" and not getattr(args, "agent_command", None):
        parser.parse_args(["agent", "--help"])
        sys.exit(1)

    args.func(args)


if __name__ == "__main__":
    main()
